// GENERATED by Scripts/generate_balance_config.py from the Godot resources/game_balance_config.gd — do not edit by
// hand (re-run the script when Godot adds parameters). The values live in /Game/Data/Balance/DA_GameBalanceConfig
// and DA_Balance and are tuned there (Unreal is the master copy since 2026-10-01).

#pragma once

#include "CoreMinimal.h"
#include "Data/GodotBalanceAsset.h"

#include "GameBalanceConfig.generated.h"

/**
 * The Godot GameBalanceConfig inspector in Unreal: every exported parameter as a typed field under its Godot name,
 * grouped like the Godot @export_group sections. UGodotBalanceAsset::GetNumber reads these fields by name, so the
 * game picks up edits made in the asset. Godot reference: resources/game_balance_config.gd.
 */
UCLASS(BlueprintType)
class CODEXTACTICS_API UGameBalanceConfig : public UGodotBalanceAsset
{
	GENERATED_BODY()

public:
	/** Шаг опыта для перехода на следующий уровень (Ур.1: 250, Ур.2: 500, Ур.3: 750, ... до 2500 на 10 уровне). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	int32 exp_per_level_step = 250;

	/** Максимальный уровень персонажа (лимит развития). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	int32 max_character_level = 10;

	/** Предельный максимум здоровья (HP Cap), выше которого здоровье нельзя прокачать. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float health_cap_limit = 200.0f;

	/** Количество свободных очков характеристик, выдаваемых бойцу при получении нового уровня. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	int32 stat_points_per_level = 3;

	/** Прирост максимального запаса здоровья (HP) за 1 вложенное очко характеристики. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float hp_per_stat_point = 5.0f;

	/** Прирост процента Удачи (%) за 1 вложенное очко характеристики (Крит x2.0, Уклонение, Лут). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float luck_per_stat_point = 1.0f;

	/** Прирост процента Меткости (%) за 1 вложенное очко характеристики (Дальность поражения). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float accuracy_per_stat_point = 1.0f;

	/** Прирост Стойкости за 1 вложенное очко характеристики (Срез урона, Сопротивление холоду, Реген). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float fortitude_per_stat_point = 1.0f;

	/** Множитель меткости в стойке СТОЯ (базовый). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float posture_accuracy_standing = 1.00f;

	/** Множитель меткости в стойке ПРИСЕВ (повышенная кучность и дальность). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float posture_accuracy_crouching = 1.15f;

	/** Множитель меткости в стойке ЛЁЖА (максимальная снайперская дальность). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float posture_accuracy_prone = 1.35f;

	/** Множитель накопления холода от ветра в стойке СТОЯ (базовый). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_cold_multiplier_standing = 1.00f;

	/** Множитель накопления холода от ветра в стойке СИДЯ (снижение обдува на 15%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_cold_multiplier_crouching = 0.85f;

	/** Множитель накопления холода от ветра в стойке ЛЁЖА (защита от ветра у земли на 40%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_cold_multiplier_prone = 0.60f;

	/** Дополнительный срез входящего урона при укрытии сидя за баррикадой (35%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float crouch_barricade_cover_reduction = 0.35f;

	/** Скорость плавного разворота корпуса в стойке СТОЯ (рад/сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_turn_speed_standing = 14.0f;

	/** Скорость плавного разворота корпуса в стойке СИДЯ (рад/сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_turn_speed_crouching = 7.5f;

	/** Скорость плавного разворота корпуса в стойке ЛЁЖА (рад/сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_turn_speed_prone = 2.5f;

	/** Задержка реакции на переключение на более близкого флангового врага в стойке СТОЯ (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_target_switch_delay_standing = 0.15f;

	/** Задержка реакции на переключение на более близкого флангового врага в стойке СИДЯ (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_target_switch_delay_crouching = 0.50f;

	/** Задержка реакции на переключение на более близкого флангового врага в стойке ЛЁЖА (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_target_switch_delay_prone = 1.20f;

	/** Порог дистанции для переключения фокуса в стойке СТОЯ (враг должен быть на 10% ближе текущего). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_switch_distance_ratio_standing = 0.90f;

	/** Порог дистанции для переключения фокуса в стойке СИДЯ (враг должен быть на 20% ближе текущего). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_switch_distance_ratio_crouching = 0.80f;

	/** Порог дистанции для переключения фокуса в стойке ЛЁЖА (враг должен быть на 35% ближе текущего). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Прокачка и Очки характеристик")
	float stance_switch_distance_ratio_prone = 0.65f;

	/** Опыт за уничтожение Ледяной гончей (снижено в 5 раз для баланса). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Награды опытом (EXP)")
	int32 exp_reward_hound = 9;

	/** Опыт за уничтожение Ледяного стрелка. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Награды опытом (EXP)")
	int32 exp_reward_spitter = 12;

	/** Опыт за уничтожение Ледяного громилы (мини-босса). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Награды опытом (EXP)")
	int32 exp_reward_brute = 30;

	/** Опыт за уничтожение Промёрзшего зомби. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Награды опытом (EXP)")
	int32 exp_reward_frostbitten = 7;

	/** Опыт всем бойцам за успешное отражение боевой волны. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Награды опытом (EXP)")
	int32 exp_reward_wave_complete = 40;

	/** Опыт за обыск и открытие ящика снабжения. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "RPG: Награды опытом (EXP)")
	int32 exp_reward_loot_crate = 10;

	/** Начальный максимальный запас здоровья (HP) Командира (база 130). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_max_health = 130.0f;

	/** Начальная Меткость Командира (%, снайперская база 90%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_accuracy = 90.0f;

	/** Начальная Удача Командира (% шанс крита и уклонения, база 25%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_luck = 25.0f;

	/** Начальная Стойкость Командира (защита от урона и холода, база 15). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_fortitude = 15.0f;

	/** Базовый урон основного оружия Командира (Автомат M16) за один выстрел. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_weapon_damage = 18.0f;

	/** Максимальная дистанция атаки Командира (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_attack_range = 14.0f;

	/** Скорострельность оружия Командира — интервал между выстрелами (в секундах). Меньше = чаще стреляет. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_fire_rate = 0.65f;

	/** Радиус тактической зоны подготовки Командира (в метрах), в пределах которой отряд может свободно перемещаться до начала боя. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	float commander_prep_radius = 15.0f;

	/** Начальный запас спичек у Командира (штук). Используются для зажигания горючих бочек и костров. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир")
	int32 commander_matches_count = 3;

	/** Множитель скорости прироста стресса Командира (0.8 = закаленный офицер, на 20% устойчивее). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир", meta = (UIMin = "0.1", UIMax = "2.0", ClampMin = "0.1", ClampMax = "2.0", Delta = "0.05"))
	float commander_stress_gain_multiplier = 0.8f;

	/** Скорость естественного успокоения Командира вне боя (очков в сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_recovery_rate = 6.0f;

	/** Порог здоровья (доля от макс. HP), ниже которого начинается сильный стресс. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир", meta = (UIMin = "0.05", UIMax = "0.5", ClampMin = "0.05", ClampMax = "0.5", Delta = "0.05"))
	float commander_panic_hp_threshold = 0.30f;

	/** Порог замерзания (доля холода) для паники. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир", meta = (UIMin = "0.5", UIMax = "0.95", ClampMin = "0.5", ClampMax = "0.95", Delta = "0.05"))
	float commander_panic_cold_threshold = 0.75f;

	/** Критический остаток патронов в магазине для боевого стресса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	int32 commander_panic_low_ammo_threshold = 5;

	/** Дистанция угрозы монстров (в метрах) для стресса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_monster_threat_distance = 7.5f;

	/** Импульс стресса при ранении союзника рядом. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_ally_down_stress = 20.0f;

	/** Скорость бегства Командира в панике (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_flee_speed = 6.2f;

	/** Дистанция первичного отбегания в панике перед тем, как сесть (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_flee_distance = 6.0f;

	/** Минимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_min_duration = 5.0f;

	/** Максимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Паника и Стресс: Командир")
	float commander_panic_max_duration = 10.0f;

	/** Базовый шанс ярости Командира при выполнении условий (0.85 = 85%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.05"))
	float commander_rage_base_chance = 0.85f;

	/** Необходимое количество полученных критов от одного врага для триггера ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир")
	int32 commander_rage_required_crits = 2;

	/** Минимальная доля здоровья для возможности войти в ярость. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир", meta = (UIMin = "0.3", UIMax = "0.9", ClampMin = "0.3", ClampMax = "0.9", Delta = "0.05"))
	float commander_rage_high_health_threshold = 0.60f;

	/** Минимальный остаток патронов для ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир")
	int32 commander_rage_min_ammo_threshold = 6;

	/** Длительность нахождения в ярости (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир")
	float commander_rage_duration = 9.0f;

	/** Множитель урона пуль во время ярости (+35%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир")
	float commander_rage_damage_multiplier = 1.35f;

	/** Множитель скорости бега в ярости (+25%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир")
	float commander_rage_speed_multiplier = 1.25f;

	/** Множитель интервала между выстрелами в ярости (0.45 = темп огня выше на 55%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Командир|Ярость и Буйство: Командир")
	float commander_rage_fire_rate_multiplier = 0.45f;

	/** Начальный максимальный запас здоровья (HP) Инженера (база 150, самый живучий боец). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_max_health = 150.0f;

	/** Начальная Меткость Инженера (%, база 75%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_accuracy = 75.0f;

	/** Начальная Удача Инженера (%, база 30%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_luck = 30.0f;

	/** Начальная Стойкость Инженера (высокая защита от урона и холода, база 25). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_fortitude = 25.0f;

	/** Базовая скорость передвижения Инженера (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_speed = 4.8f;

	/** Базовый урон основного оружия Инженера (Винтовка FN FAL) за выстрел. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_weapon_damage = 22.0f;

	/** Максимальная дистанция атаки Инженера (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_attack_range = 12.0f;

	/** Скорострельность Инженера — интервал между выстрелами (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	float engineer_fire_rate = 0.80f;

	/** Начальное количество переносных баррикад в инвентаре Инженера (штук). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	int32 engineer_barricades_count = 0;

	/** Начальный запас спичек у Инженера (штук). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер")
	int32 engineer_matches_count = 3;

	/** Множитель скорости прироста стресса Инженера (1.1 = нервничает чуть сильнее). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер", meta = (UIMin = "0.1", UIMax = "2.0", ClampMin = "0.1", ClampMax = "2.0", Delta = "0.05"))
	float engineer_stress_gain_multiplier = 1.1f;

	/** Скорость естественного успокоения Инженера вне боя (очков в сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_recovery_rate = 4.5f;

	/** Порог здоровья для стресса Инженера. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер", meta = (UIMin = "0.05", UIMax = "0.5", ClampMin = "0.05", ClampMax = "0.5", Delta = "0.05"))
	float engineer_panic_hp_threshold = 0.40f;

	/** Порог замерзания для паники. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер", meta = (UIMin = "0.5", UIMax = "0.95", ClampMin = "0.5", ClampMax = "0.95", Delta = "0.05"))
	float engineer_panic_cold_threshold = 0.65f;

	/** Критический остаток патронов для стресса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	int32 engineer_panic_low_ammo_threshold = 6;

	/** Дистанция угрозы монстров для стресса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_monster_threat_distance = 8.5f;

	/** Импульс стресса при ранении союзника рядом. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_ally_down_stress = 30.0f;

	/** Скорость бегства Инженера в панике (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_flee_speed = 5.8f;

	/** Дистанция первичного отбегания в панике перед тем, как сесть (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_flee_distance = 7.0f;

	/** Минимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_min_duration = 6.5f;

	/** Максимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Паника и Стресс: Инженер")
	float engineer_panic_max_duration = 13.0f;

	/** Базовый шанс ярости Инженера при выполнении условий (0.70 = 70%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.05"))
	float engineer_rage_base_chance = 0.70f;

	/** Необходимое количество полученных критов от одного врага для триггера ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер")
	int32 engineer_rage_required_crits = 3;

	/** Минимальная доля здоровья для возможности войти в ярость. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер", meta = (UIMin = "0.3", UIMax = "0.9", ClampMin = "0.3", ClampMax = "0.9", Delta = "0.05"))
	float engineer_rage_high_health_threshold = 0.70f;

	/** Минимальный остаток патронов для ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер")
	int32 engineer_rage_min_ammo_threshold = 6;

	/** Длительность нахождения в ярости (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер")
	float engineer_rage_duration = 7.5f;

	/** Множитель урона пуль во время ярости (+25%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер")
	float engineer_rage_damage_multiplier = 1.25f;

	/** Множитель скорости бега в ярости (+20%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер")
	float engineer_rage_speed_multiplier = 1.20f;

	/** Множитель интервала между выстрелами в ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Инженер|Ярость и Буйство: Инженер")
	float engineer_rage_fire_rate_multiplier = 0.50f;

	/** Начальный максимальный запас здоровья (HP) Медика-сапёра (база 120). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_max_health = 120.0f;

	/** Начальная Меткость Медика-сапёра (%, база 85%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_accuracy = 85.0f;

	/** Начальная Удача Медика-сапёра (высокий крит и уклонение, база 35%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_luck = 35.0f;

	/** Начальная Стойкость Медика-сапёра (база 20). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_fortitude = 20.0f;

	/** Базовая скорость передвижения Медика-сапёра (м/с, самый мобильный боец). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_speed = 5.2f;

	/** Базовый урон оружия Медика (ПП MP5) за выстрел. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_weapon_damage = 14.0f;

	/** Максимальная дистанция стрельбы Медика-сапёра (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_attack_range = 15.0f;

	/** Скорострельность Медика — интервал между выстрелами (в секундах). Высокий темп огня. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	float medic_fire_rate = 0.55f;

	/** Начальное количество полевых аптечек у Медика (штук). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	int32 medic_medkits_count = 2;

	/** Начальное количество противопехотных мин у Медика-сапёра (штук). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	int32 medic_mines_count = 0;

	/** Начальный запас спичек у Медика-сапёра (штук). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр")
	int32 medic_matches_count = 3;

	/** Множитель скорости прироста стресса Медика-сапёра (0.9 = высокая психологическая закалка). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр", meta = (UIMin = "0.1", UIMax = "2.0", ClampMin = "0.1", ClampMax = "2.0", Delta = "0.05"))
	float medic_stress_gain_multiplier = 0.9f;

	/** Скорость естественного успокоения Медика-сапёра вне боя (очков в сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_recovery_rate = 5.5f;

	/** Порог здоровья для стресса Медика-сапёра. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр", meta = (UIMin = "0.05", UIMax = "0.5", ClampMin = "0.05", ClampMax = "0.5", Delta = "0.05"))
	float medic_panic_hp_threshold = 0.35f;

	/** Порог замерзания для паники. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр", meta = (UIMin = "0.5", UIMax = "0.95", ClampMin = "0.5", ClampMax = "0.95", Delta = "0.05"))
	float medic_panic_cold_threshold = 0.70f;

	/** Критический остаток патронов для стресса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	int32 medic_panic_low_ammo_threshold = 5;

	/** Дистанция угрозы монстров для стресса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_monster_threat_distance = 7.0f;

	/** Импульс стресса при ранении союзника рядом. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_ally_down_stress = 22.0f;

	/** Скорость бегства Медика-сапёра в панике (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_flee_speed = 6.4f;

	/** Дистанция первичного отбегания в панике перед тем, как сесть (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_flee_distance = 6.5f;

	/** Минимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_min_duration = 5.5f;

	/** Максимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Паника и Стресс: Медик-сапёр")
	float medic_panic_max_duration = 11.0f;

	/** Базовый шанс ярости Медика-сапёра при выполнении условий (0.80 = 80%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.05"))
	float medic_rage_base_chance = 0.80f;

	/** Необходимое количество полученных критов от одного врага для триггера ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр")
	int32 medic_rage_required_crits = 2;

	/** Минимальная доля здоровья для возможности войти в ярость. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр", meta = (UIMin = "0.3", UIMax = "0.9", ClampMin = "0.3", ClampMax = "0.9", Delta = "0.05"))
	float medic_rage_high_health_threshold = 0.65f;

	/** Минимальный остаток патронов для ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр")
	int32 medic_rage_min_ammo_threshold = 6;

	/** Длительность нахождения в ярости (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр")
	float medic_rage_duration = 8.5f;

	/** Множитель урона пуль во время ярости (+30%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр")
	float medic_rage_damage_multiplier = 1.30f;

	/** Множитель скорости бега в ярости (+30%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр")
	float medic_rage_speed_multiplier = 1.30f;

	/** Множитель интервала между выстрелами в ярости (0.40 = высокий темп). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Медик-сапёр|Ярость и Буйство: Медик-сапёр")
	float medic_rage_fire_rate_multiplier = 0.40f;

	/** Начальный максимальный запас здоровья (HP) Ивана Сусанина (база 110.0). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)")
	float susanin_max_health = 110.0f;

	/** Базовая скорость передвижения Ивана Сусанина (м/с, синхронизирована со стандартом командира). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)")
	float susanin_speed = 2.2f;

	/** Начальная Меткость Ивана Сусанина (%, база 70%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)")
	float susanin_accuracy = 70.0f;

	/** Начальная Удача Ивана Сусанина (база 45%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)")
	float susanin_luck = 45.0f;

	/** Начальная Стойкость Ивана Сусанина (база 30.0; снижает скорость накопления стресса). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)")
	float susanin_fortitude = 30.0f;

	/** Множитель скорости прироста стресса Сусанина (0.5 = в 2 раза медленнее паникует). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин", meta = (UIMin = "0.1", UIMax = "2.0", ClampMin = "0.1", ClampMax = "2.0", Delta = "0.05"))
	float susanin_stress_gain_multiplier = 0.5f;

	/** Скорость естественного успокоения Сусанина (очков в сек, успокаивается быстро). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_recovery_rate = 7.5f;

	/** Скорость успокоения (алиас-множитель для обратной совместимости, 1.5x). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_recovery_mult = 1.5f;

	/** Порог HP для паники Сусанина (0.25 = паникует только при здоровье ниже 25%, а не стандартных 35%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин", meta = (UIMin = "0.05", UIMax = "0.5", ClampMin = "0.05", ClampMax = "0.5", Delta = "0.05"))
	float susanin_panic_hp_threshold = 0.25f;

	/** Алиас для обратной совместимости */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_hp_panic_threshold = 0.25f;

	/** Порог замерзания (доля холода) для паники Сусанина (0.80 = привык к морозу). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин", meta = (UIMin = "0.5", UIMax = "0.95", ClampMin = "0.5", ClampMax = "0.95", Delta = "0.05"))
	float susanin_panic_cold_threshold = 0.80f;

	/** Критический остаток патронов (0 = Сусанин боец ближнего боя с ножом, нет стресса от патронов). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	int32 susanin_panic_low_ammo_threshold = 0;

	/** Дистанция угрозы монстров для Сусанина (в метрах; 4.5м позволяет сближаться с ножом без паники). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_monster_threat_distance = 4.5f;

	/** Алиас для обратной совместимости */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_monster_threat_distance = 4.5f;

	/** Импульс стресса при ранении союзника рядом. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_ally_down_stress = 20.0f;

	/** Скорость бегства Сусанина в панике (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_flee_speed = 5.5f;

	/** Дистанция первичного отбегания в панике перед тем, как сесть (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_flee_distance = 5.0f;

	/** Минимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_min_duration = 4.5f;

	/** Максимальная длительность паники (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Паника и Стресс: Иван Сусанин")
	float susanin_panic_max_duration = 9.0f;

	/** Базовый шанс ярости Сусанина при выполнении условий (0.85 = 85%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.05"))
	float susanin_rage_base_chance = 0.85f;

	/** Необходимое количество полученных критов от одного врага для триггера ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин")
	int32 susanin_rage_required_crits = 2;

	/** Минимальная доля здоровья для возможности войти в ярость. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин", meta = (UIMin = "0.2", UIMax = "0.9", ClampMin = "0.2", ClampMax = "0.9", Delta = "0.05"))
	float susanin_rage_high_health_threshold = 0.50f;

	/** Минимальный остаток патронов (0 = нож, не требует патронов). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин")
	int32 susanin_rage_min_ammo_threshold = 0;

	/** Длительность нахождения в ярости (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин")
	float susanin_rage_duration = 10.0f;

	/** Множитель урона ножа во время ярости (+50%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин")
	float susanin_rage_damage_multiplier = 1.50f;

	/** Множитель скорости бега в ярости (+35%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин")
	float susanin_rage_speed_multiplier = 1.35f;

	/** Множитель интервала между ударами в ярости (0.35 = частые удары). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "ОТРЯД: Иван Сусанин (Рекрут)|Ярость и Буйство: Иван Сусанин")
	float susanin_rage_fire_rate_multiplier = 0.35f;

	/** Урон автоматической винтовки M16 (Кинетический урон, универсальное оружие). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_m16_damage = 18.0f;

	/** Урон дробовика Remington (Кинетический урон в упор). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_shotgun_damage = 45.0f;

	/** Урон тактического ножа (Ближний бой, накладывает статус Кровотечение). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_knife_damage = 22.0f;

	/** Урон тяжелой кувалды (Ближний бой, накладывает оглушение Stagger и срывает броню). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_hammer_damage = 65.0f;

	/** Урон огнемета «Прометей» (Огненный урон, накладывает горение DoT, плавит панцири, согревает стрелка). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_flame_damage = 32.0f;

	/** Урон крио-излучателя «Абсолют» (Криогенный урон, замедляет врагов, 0x по ледяным монстрам, морозит стрелка). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_cryo_damage = 16.0f;

	/** Урон плазменного карабина «Спектр» (Энергетический урон, двойной урон x2.0 по Ледяным Громилам, пробивает броню). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Арсенал и Оружие")
	float weapon_plasma_damage = 28.0f;

	/** Скорость плавного разворота бойцов в сторону движения/цели (рад/сек). Исключает резкие мгновенные повороты. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Передвижение отряда")
	float character_turn_speed = 12.0f;

	/** Множитель скорости бега (спринта) при двойном клике (1.65 = 165% от базовой скорости ходьбы). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Передвижение отряда")
	float sprint_speed_multiplier = 1.65f;

	/** Предельный уровень холода (%), выше которого боец считается замерзшим и не может бежать спринтом. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Передвижение отряда")
	float max_cold_to_sprint = 60.0f;

	/** Ускорение набора скорости бойцами при старте движения и переходе с шага на бег (м/с²). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Передвижение отряда")
	float character_acceleration = 14.0f;

	/** Замедление / торможение бойцов при плавной остановке и переходе с бега на шаг (м/с²). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Передвижение отряда")
	float character_deceleration = 18.0f;

	/** Скорость накопления холода на открытом морозе (в % за секунду). Чем выше, тем быстрее замерзают бойцы. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика холода")
	float cold_accumulation_rate = 0.30f;

	/** Скорость восстановления тепла и сброса холода вблизи активного источника тепла (бочки, генератора) в % за секунду. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика холода")
	float cold_warmth_recovery_rate = 8.0f;

	/** Эффективный радиус действия тепловой зоны костра/бочки/генератора (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика холода")
	float warmth_effective_distance = 4.5f;

	/** Предельный уровень холода (%), выше которого боец считается тяжело обмороженным и не может поднимать/толкать тяжелые объекты. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика холода")
	float max_cold_to_lift_objects = 80.0f;

	/** Порог тяжелого ранения (доля от максимального HP, например 0.50 = 50% HP). Ниже этого порога боец хромает и слабеет. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика ранений")
	float wounded_health_threshold_percent = 0.50f;

	/** Множитель скорости передвижения при тяжелом ранении (< 50% HP). Например, 0.65 = боец идет со скоростью 65% от нормы. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика ранений")
	float wounded_speed_multiplier = 0.65f;

	/** Минимальный процент здоровья (HP), необходимый для возможности толкать/перемещать тяжелые объекты. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика ранений")
	float min_health_percent_to_lift = 0.50f;

	/** Множитель скорости передвижения бойца во время толкания тяжелых объектов (0.30 = 30% от базовой скорости, замедление более чем в 3 раза). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Механика переноса объектов")
	float carrying_speed_multiplier = 0.30f;

	/** Запас прочности автоматической турели (HP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Автоматическая турель")
	float turret_max_health = 120.0f;

	/** Урон одного выстрела турели по врагам. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Автоматическая турель")
	float turret_damage = 16.0f;

	/** Скорострельность турели — интервал между выстрелами (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Автоматическая турель")
	float turret_fire_rate = 0.45f;

	/** Радиус автоматического обнаружения и обстрела врагов турелью (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Автоматическая турель")
	float turret_attack_range = 12.0f;

	/** Прочность развернутой тактической баррикады (HP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Баррикада")
	float barricade_max_health = 120.0f;

	/** Снижение входящего урона для бойца, находящегося в укрытии за баррикадой (0.40 = поглощает 40% урона). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Баррикада")
	float barricade_cover_damage_reduction = 0.40f;

	/** Максимальный урон в эпицентре взрыва противопехотной мины. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Противопехотная мина")
	float mine_explosion_damage = 85.0f;

	/** Радиус поражения взрывной волной и осколками мины (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Противопехотная мина")
	float mine_explosion_radius = 4.5f;

	/** Радиус срабатывания детонатора при приближении врага к мине (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Противопехотная мина")
	float mine_trigger_radius = 1.6f;

	/** Базовая дистанция обнаружения скрытых мин бойцом при ходьбе (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Противопехотная мина")
	float mine_detection_range = 4.5f;

	/** Профессиональный бонус сапёра к дальности обнаружения мин (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Противопехотная мина")
	float mine_sapper_detection_bonus = 1.5f;

	/** Количество восстанавливаемого здоровья при использовании полевой аптечки (HP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Постройки и способности|Аптечка")
	float medkit_heal_amount = 45.0f;

	/** Включена ли рандомизация фазы (случайное смещение старта анимации) при беге/покое врагов. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общие параметры анимации врагов")
	bool enemy_anim_phase_randomization = true;

	/** Индивидуальный органический разброс скорости анимации бега врагов (±6% для стайных врагов). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общие параметры анимации врагов")
	float enemy_anim_speed_jitter = 0.06f;

	/** Атакуют ли враги союзные турели как полноценные боевые цели. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Реакция на турели и огонь")
	bool enemy_target_turrets = true;

	/** Дистанция приоритетного переключения аггро на турель (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Реакция на турели и огонь")
	float enemy_turret_threat_distance = 10.0f;

	/** Включен ли панический страх огня и горящих бочек у малых врагов (гончие, каттеры, промёрзшие). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Реакция на турели и огонь")
	bool enemy_fire_fear_enabled = true;

	/** Радиус панического страха огня (в метрах), ближе которого малые враги отбегают от пламени. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Реакция на турели и огонь")
	float enemy_fire_fear_radius = 6.0f;

	/** Множитель скорости бегства малых врагов от источника огня (1.20 = +20% ускорение в панике). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Реакция на турели и огонь")
	float enemy_fire_fear_flee_speed_mult = 1.20f;

	/** Здоровье Ледяной гончей (быстрый, но хрупкий враг ближнего боя). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяная гончая")
	float hound_health = 45.0f;

	/** Скорость бега гончей (м/с). Быстрее бойцов отряда. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяная гончая")
	float hound_speed = 5.4f;

	/** Урон одного укуса гончей. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяная гончая")
	float hound_damage = 12.0f;

	/** Дистанция удара когтями/укуса гончей (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяная гончая")
	float hound_attack_range = 1.8f;

	/** Перезарядка между атаками гончей (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяная гончая")
	float hound_attack_cooldown = 1.0f;

	/** Здоровье Ледяного стрелка (дальнобойный ледяной монстр). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной стрелок")
	float spitter_health = 70.0f;

	/** Скорость передвижения стрелка (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной стрелок")
	float spitter_speed = 3.2f;

	/** Урон ледяного снаряда стрелка. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной стрелок")
	float spitter_damage = 18.0f;

	/** Предпочитаемая дистанция удержания позиции стрелком (в метрах, кайтит отряд). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной стрелок")
	float spitter_preferred_range = 12.0f;

	/** Максимальная дальность стрельбы ледяными шипами (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной стрелок")
	float spitter_attack_range = 15.0f;

	/** Интервал между залпами ледяных шипов стрелка (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной стрелок")
	float spitter_shoot_interval = 2.2f;

	/** Запас здоровья Ледяного громилы (тяжелый босс/мини-босс ближнего боя). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной громила")
	float brute_health = 220.0f;

	/** Скорость ходьбы громилы (м/с, медленный, но неудержимый). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной громила")
	float brute_speed = 1.8f;

	/** Базовый урон сокрушительного удара громилы по персонажам. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной громила")
	float brute_damage = 35.0f;

	/** Множитель урона громилы по баррикадам и укреплениям (быстро разрушает укрытия). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной громила")
	float brute_barricade_damage_multiplier = 2.0f;

	/** Дистанция сокрушительного удара громилы (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной громила")
	float brute_attack_range = 2.4f;

	/** Перезарядка мощного удара громилы (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Враги: Ледяной громила")
	float brute_attack_cooldown = 2.0f;

	/** Длительность фазы подготовки к обороне перед стартом боевой волны (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны")
	float preparation_phase_duration = 60.0f;

	/** Длительность передышки между волнами (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны")
	float wave_rest_duration = 20.0f;

	/** Общее количество волн в кампании до финальной победы. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны")
	int32 max_campaign_waves = 10;

	/** Минимальное гарантированное число врагов в любой волне. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 min_enemies_per_wave = 3;

	/** Базовое количество врагов для 1-й волны. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 base_wave_enemy_count = 3;

	/** Прирост числа врагов за каждую последующую волну (+N врагов за волну). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 enemy_count_per_wave_growth = 2;

	/** Максимальный лимит врагов, спавнящихся за одну волну. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 max_enemies_per_wave = 16;

	/** Минимальное число быстрых гончих в составе волны. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 min_hounds_per_wave = 2;

	/** Минимальное число стрелков в составе волны. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 min_spitters_per_wave = 1;

	/** Номер волны, начиная с которой на карте появляются тяжелые Громилы. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 brute_start_wave = 3;

	/** Минимальное количество Громил в волне (начиная с волны brute_start_wave). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Режимы и волны|Генерация врагов в волнах")
	int32 min_brutes_per_wave = 1;

	/** Скорость плавного следования камеры за лидером отряда (интерполяция позиции). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_follow_speed = 6.0f;

	/** Длительность мягкого кинематографичного возврата угла вращения (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_rotation_return_duration = 0.95f;

	/** Длительность мягкого возврата панорамирования в центр при исследовании (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_pan_return_duration = 0.85f;

	/** Скорость свободного перемещения камеры клавишами WASD и краями экрана (м/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_pan_speed = 20.0f;

	/** Базовый максимальный радиус панорамирования камеры от лидера в режиме исследования (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_max_pan_distance = 35.0f;

	/** Чувствительность вращения камеры при зажатой правой кнопке мыши (ПКМ). Меньше = мягче поворот. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_rmb_rotation_sensitivity = 0.003f;

	/** Чувствительность панорамирования сцены при зажатом колесике мыши (СКМ). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_mmb_pan_sensitivity = 0.015f;

	/** Коэффициент сглаживания вращения камеры (устранение микрорывков мыши). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_rotation_smooth_speed = 9.0f;

	/** Коэффициент сглаживания панорамирования сцены. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой")
	float camera_pan_smooth_speed = 7.0f;

	/** Базовое расстояние камеры от персонажа на этапе исследования (в метрах). Меньше = камера ближе к игроку для детального обзора. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Дистанция камеры: Исследование vs Бой")
	float camera_distance_exploration = 16.0f;

	/** Базовое расстояние камеры от персонажа на этапе боя (в метрах). Больше = широкий тактический обзор поля боя. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Дистанция камеры: Исследование vs Бой")
	float camera_distance_combat = 28.0f;

	/** Минимально допустимое расстояние приближения камеры колесиком мыши (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Дистанция камеры: Исследование vs Бой")
	float camera_distance_min = 8.0f;

	/** Максимально допустимое расстояние отдаления камеры колесиком мыши (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Дистанция камеры: Исследование vs Бой")
	float camera_distance_max = 40.0f;

	/** Минимальный коэффициент приближения камеры (максимальный Zoom In). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Зуммирование камеры")
	float camera_min_zoom = 0.55f;

	/** Максимальный коэффициент отдаления камеры (максимальный Zoom Out). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Зуммирование камеры")
	float camera_max_zoom = 2.2f;

	/** Шаг зума за один щелчок колесика мыши. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Зуммирование камеры")
	float camera_zoom_step = 0.12f;

	/** Скорость плавного приближения и отдаления камеры (Smooth Zoom). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Управление камерой|Зуммирование камеры")
	float camera_zoom_smooth_speed = 6.0f;

	/** Амплитуда естественного рыскания ведомых бойцов в строю по ширине влево/вправо (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	float formation_wander_amplitude_side = 0.6f;

	/** Амплитуда естественного смещения ведомых вперед/назад в строю (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	float formation_wander_amplitude_back = 0.5f;

	/** Частота естественных волнообразных колебаний в строю (рад/с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	float formation_wander_frequency = 1.2f;

	/** Вариация скорости ходьбы ведомых бойцов (±12% для живого дыхания темпа). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	float formation_wander_speed_jitter = 0.12f;

	/** Множитель скорости догона при возврате ведомых в строй (1.15 = не быстрее +15% от скорости шага/стойки командира). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	float follower_regroup_speed_multiplier = 1.15f;

	/** Скорость сглаживания поворота строя при смене направления командира (рад/с). Предотвращает мгновенное смещение слотов. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	float formation_rotation_smoothing = 3.5f;

	/** Включено ли умное перераспределение слотов строя при развороте (ближайший боец занимает ближайший фланг). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Органическое перемещение отряда и строй")
	bool formation_smart_slot_assignment = true;

	/** Время неподвижности отряда (в секундах) до начала самостоятельного патрулирования и осмотра периметра ведомыми. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Поведение бойцов при простое")
	float follower_idle_roam_delay = 40.0f;

	/** Максимальный радиус удаления ведомых бойцов от командира при осмотре и патрулировании на месте (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Поведение бойцов при простое")
	float follower_idle_roam_radius = 4.0f;

	/** Минимальный интервал смены точки или сектора осмотра в режиме простоя (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Поведение бойцов при простое")
	float follower_idle_spot_interval_min = 4.0f;

	/** Максимальный интервал смены точки или сектора осмотра в режиме простоя (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Поведение бойцов при простое")
	float follower_idle_spot_interval_max = 8.0f;

	/** Смещение панели реплик от правого края экрана (в пикселях, отрицательное значение сдвигает влево от границы). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Интерфейс реплик и диалогов")
	float dialog_panel_offset_x = -20.0f;

	/** Смещение панели реплик от верхнего края экрана (в пикселях). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Интерфейс реплик и диалогов")
	float dialog_panel_offset_y = 20.0f;

	/** Ширина панели реплик (в пикселях). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Интерфейс реплик и диалогов")
	float dialog_panel_width = 440.0f;

	/** Высота панели реплик (в пикселях). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Интерфейс реплик и диалогов")
	float dialog_panel_height = 120.0f;

	/** Включить/выключить отображение тактического конуса зрения для всех бойцов отряда. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Визуализация конуса зрения")
	bool show_vision_cones = true;

	/** Дальность сектора обзора конуса зрения (в метрах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Визуализация конуса зрения")
	float vision_cone_range = 14.0f;

	/** Угол сектора обзора конуса зрения (в градусах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Визуализация конуса зрения")
	float vision_cone_angle = 70.0f;

	/** Максимальное количество бойцов в отряде, которые могут одновременно находиться в состоянии паники (ограничение хаоса). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	int32 panic_max_panicked_members = 2;

	/** Скорость снижения стресса у бойцов рядом со спокойным командиром (аура лидерства, очков в сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float panic_friendly_leader_aura_reduction = 10.0f;

	/** Скорость снятия стресса при нахождении в зоне тепла костра (очков стресса в секунду). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float panic_heat_source_calm_rate = 25.0f;

	/** Время непрерывного нахождения у источника тепла (в секундах) для досрочного полного выхода из паники. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float panic_heat_source_panic_break_time = 2.5f;

	/** Приоритет выбора направления бегства в сторону спасительного тепла (0.0 = только от врагов, 1.0 = строго к теплу). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.05"))
	float panic_flee_towards_heat_bias = 0.5f;

	/** Максимальный радиус отдаления бойца в панике от отряда / командира (в метрах, предотвращает разбег по всей карте). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float panic_max_flee_radius = 15.0f;

	/** Дистанция отрыва от врагов (в метрах), на которой боец чувствует себя в безопасности и быстрее успокаивается. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float panic_recover_distance_from_enemies = 15.0f;

	/** Окно памяти критических ударов от одного врага (в секундах). Если интервал больше, счетчик сбрасывается. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float rage_crit_memory_window = 25.0f;

	/** Спад шанса ярости за время активного боя (снижает шанс примерно на 10% в минуту боя). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float rage_combat_decay_rate = 0.10f;

	/** Минимальный гарантированный порог шанса на ярость (ниже которого шанс не падает). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.05"))
	float rage_min_chance = 0.15f;

	/** Бесконечный непрерывный полив огнем без задержек на перезарядку во время ярости. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	bool rage_infinite_ammo = true;

	/** Частота переключения целей при хаотичном веерном поливе огнем (в секундах). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла")
	float rage_chaotic_target_switch_time = 0.55f;

	/** panic_hp_threshold */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_hp_threshold = 0.35f;

	/** panic_cold_threshold */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_cold_threshold = 0.70f;

	/** panic_low_ammo_threshold */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	int32 panic_low_ammo_threshold = 5;

	/** panic_monster_threat_distance */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_monster_threat_distance = 8.0f;

	/** panic_ally_down_stress */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_ally_down_stress = 25.0f;

	/** panic_fortitude_resistance_weight */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_fortitude_resistance_weight = 2.5f;

	/** panic_stress_recovery_rate */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_stress_recovery_rate = 5.0f;

	/** panic_speed_multiplier */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_speed_multiplier = 1.25f;

	/** panic_flee_speed */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_flee_speed = 6.0f;

	/** panic_flee_distance */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_flee_distance = 6.5f;

	/** panic_flee_max_time */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_flee_max_time = 2.2f;

	/** panic_min_duration */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_min_duration = 6.0f;

	/** panic_max_duration */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float panic_max_duration = 12.0f;

	/** rage_base_chance */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float rage_base_chance = 0.80f;

	/** rage_required_crits */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	int32 rage_required_crits = 2;

	/** rage_high_health_threshold */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float rage_high_health_threshold = 0.65f;

	/** rage_min_ammo_threshold */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	int32 rage_min_ammo_threshold = 6;

	/** rage_duration */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float rage_duration = 8.5f;

	/** rage_fire_rate_multiplier */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float rage_fire_rate_multiplier = 0.45f;

	/** rage_bullet_damage_multiplier */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float rage_bullet_damage_multiplier = 1.30f;

	/** rage_movement_speed_multiplier */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Общеотрядные правила паники и тепла|Системные значения по умолчанию (Фоллбэки)")
	float rage_movement_speed_multiplier = 1.25f;

	/** Базовый глобальный шанс критического удара для всех типов врагов (0.20 = 20%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Критические удары врагов (Enemy Critical Hits)", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.01"))
	float enemy_crit_chance = 0.20f;

	/** Множитель урона при критическом попадании врага (1.75 = +75% урона). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Критические удары врагов (Enemy Critical Hits)")
	float enemy_crit_multiplier = 1.75f;

	/** Индивидуальный шанс крита для Ледяной Гончей (HOUND). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Критические удары врагов (Enemy Critical Hits)", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.01"))
	float hound_crit_chance = 0.15f;

	/** Индивидуальный шанс крита для Ледяного Стрелка (SPITTER). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Критические удары врагов (Enemy Critical Hits)", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.01"))
	float spitter_crit_chance = 0.25f;

	/** Индивидуальный шанс крита для Ледяного Громилы (BRUTE). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Критические удары врагов (Enemy Critical Hits)", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.01"))
	float brute_crit_chance = 0.30f;

	/** Индивидуальный шанс крита для Промёрзшего (FROSTBITTEN). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Критические удары врагов (Enemy Critical Hits)", meta = (UIMin = "0.0", UIMax = "1.0", ClampMin = "0.0", ClampMax = "1.0", Delta = "0.01"))
	float frostbitten_crit_chance = 0.10f;

	/** Базовая скорость ходьбы (м/с) — единый параметр физической скорости шага бойцов и калибровки анимации ходьбы. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_walk_speed = 8.0f;

	/** Скорость бега / спринта (м/с) — единый параметр физической скорости бега бойцов и калибровки анимации спринта. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_run_speed = 13.2f;

	/** Скорость перемещения в приседе (м/с) — единый параметр физической скорости и калибровки анимации приседа. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_crouch_speed = 4.0f;

	/** Множитель частоты шагов при ходьбе (TimeScale). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_walk_timescale = 1.3f;

	/** Множитель частоты шагов при спринте / марш-броске (TimeScale). Задает быстрый темп перестановки ног. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_run_timescale = 2.4f;

	/** Множитель частоты перемещения в приседе (TimeScale). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_crouch_timescale = 1.1f;

	/** Скорость сглаживания интерполяции векторов BlendSpace2D (разгон анимации). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_blend_acceleration = 8.0f;

	/** Коэффициент затухания анимации при торможении / остановке. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_stop_damping = 12.0f;

	/** Максимальная скорость вращения корпуса при довороте (°/сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_max_turn_speed_deg = 420.0f;

	/** Порог угла для срабатывания переступания ног на месте (°). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_turn_threshold_deg = 35.0f;

	/** Коэффициент сглаживания доворота корпуса. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_turn_smoothing = 10.0f;

	/** Включена ли система поворотов на месте с переставлением ног (Turn in Place). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	bool turn_in_place_enabled = true;

	/** Минимальный угол расхождения взгляда и корпуса для запуска шагов поворота (°). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float turn_in_place_min_angle_deg = 25.0f;

	/** Скорость воспроизведения анимаций переступания ног при повороте. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float turn_in_place_speed_scale = 1.0f;

	/** Минимальный угол, при котором сидящий персонаж делает маскированный шаг поворота (°). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float crouch_turn_min_angle_deg = 5.0f;

	/** Минимальная доля длительности 90° клипа для короткого поворота сидя. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)", meta = (UIMin = "0.25", UIMax = "1.0", ClampMin = "0.25", ClampMax = "1.0", Delta = "0.05"))
	float crouch_turn_min_duration_ratio = 0.45f;

	/** Время мягкого возврата ног из финальной позы поворота в Crouch Idle (сек.). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)", meta = (UIMin = "0.05", UIMax = "0.5", ClampMin = "0.05", ClampMax = "0.5", Delta = "0.01"))
	float crouch_turn_blend_out_time = 0.18f;

	/** Включена ли адаптация подошв к рельефу (Foot Placement IK). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	bool anim_foot_ik_enabled = true;

	/** Скорость корректировки высоты стоп по лучам. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_foot_correction_speed = 10.0f;

	/** Максимальное смещение стопы вверх/вниз при шаге (м). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_max_step_offset = 0.35f;

	/** Включена ли стартовая расфазировка и органическая вариация темпа шага бойцов отряда. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	bool anim_stride_desync_enabled = true;

	/** Диапазон органического разброса темпа шагов бойцов (±5% к TimeScale, исключая бег "в ногу"). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Анимация и Передвижение (Locomotion)")
	float anim_stride_jitter_range = 0.05f;

	/** Включена ли механика перелазания через низкие баррикады и препятствия. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	bool vault_enabled = true;

	/** Максимальная высота препятствия для перелазания (м). Если преграда выше, боец её не преодолевает. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_max_height = 1.05f;

	/** Дистанция приближения к препятствию для срабатывания перемаха (м). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_approach_distance = 1.25f;

	/** Множитель скорости анимации и перемещения через препятствие. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_speed_scale = 1.15f;

	/** Преодолевают ли ведомые препятствия только при явной необходимости (когда путь преграждён). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	bool follower_vault_only_when_blocked = true;

	/** Дополнительный запас высоты подъема дуги над верхней кромкой препятствия (м). Пик траектории = измеренная высота препятствия + vault_apex_height_offset. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_apex_height_offset = 0.15f;

	/** Дистанция приземления за препятствием от точки столкновения (м). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_landing_distance = 1.35f;

	/** Длительность фазы перемаха при беге (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_run_duration = 0.95f;

	/** Длительность фазы перемаха при шаге (сек). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_walk_duration = 1.25f;

	/** Форма параболы подъема дуги (степень синусоиды: 1.0 = гладкая дуга, >1.0 = зависание в пике). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	float vault_arc_power = 1.0f;

	/** Разрешать ли просачивание пешком сквозь баррикады при застревании (false = баррикады физически твердые). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Преодоление препятствий (Vaulting)")
	bool allow_barricade_phasing = false;

	/** Минимальный размер скопления врагов в зоне поражения для автоброска ИИ (по умолчанию 3 врага). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Боевой ИИ: Метание гранат", meta = (UIMin = "1", UIMax = "10", ClampMin = "1", ClampMax = "10"))
	int32 ai_grenade_min_cluster = 3;

	/** Индивидуальный кулдаун на автобросок гранаты ИИ (секунды, по умолчанию 3.0с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Боевой ИИ: Метание гранат", meta = (UIMin = "0.5", UIMax = "30.0", ClampMin = "0.5", ClampMax = "30.0", Delta = "0.5"))
	float ai_grenade_cooldown = 3.0f;

	/** Минимальная безопасная дистанция от бросающего до эпицентра взрыва (метры, по умолчанию 5.0м). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Боевой ИИ: Метание гранат", meta = (UIMin = "1.0", UIMax = "15.0", ClampMin = "1.0", ClampMax = "15.0", Delta = "0.5"))
	float ai_grenade_min_thrower_dist = 5.0f;

	/** Радиус проверки союзников для предотвращения дружественного огня (Friendly-Fire, по умолчанию 5.0м). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Боевой ИИ: Метание гранат", meta = (UIMin = "1.0", UIMax = "15.0", ClampMin = "1.0", ClampMax = "15.0", Delta = "0.5"))
	float ai_grenade_friendly_fire_radius = 5.0f;

	/** Длительность перемещения бойца на 1 клетку сетки (секунды, по умолчанию 0.52с). Чем больше значение, тем плавнее и медленнее шаг бойца по клеткам. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.2", UIMax = "1.5", ClampMin = "0.2", ClampMax = "1.5", Delta = "0.02"))
	float tactical_step_duration = 0.52f;

	/** Длительность перемещения врага на 1 клетку сетки (секунды, по умолчанию 0.48с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.2", UIMax = "1.5", ClampMin = "0.2", ClampMax = "1.5", Delta = "0.02"))
	float tactical_enemy_step_duration = 0.48f;

	/** Размер стороны квадратной ячейки тактической сетки (метры, по умолчанию 1.5м). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.5", UIMax = "3.0", ClampMin = "0.5", ClampMax = "3.0", Delta = "0.1"))
	float tactical_cell_size = 1.5f;

	/** Высота подъема сетки над полом во избежание Z-fighting (метры, по умолчанию 0.02м / 2см). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.005", UIMax = "0.1", ClampMin = "0.005", ClampMax = "0.1", Delta = "0.005"))
	float tactical_grid_elevation = 0.02f;

	/** Максимальный запас очков действия (AP) бойцов отряда на ход. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "2", UIMax = "20", ClampMin = "2", ClampMax = "20"))
	int32 tactical_squad_max_ap = 8;

	/** Запас очков действия (AP) врагов на ход. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "2", UIMax = "20", ClampMin = "2", ClampMax = "20"))
	int32 tactical_enemy_max_ap = 6;

	/** Стоимость перемещения на 1 ортогональную клетку (очки действия AP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1", UIMax = "5", ClampMin = "1", ClampMax = "5"))
	int32 tactical_ap_cost_move = 1;

	/** Стоимость перемещения на 1 диагональную клетку (очки действия AP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1", UIMax = "5", ClampMin = "1", ClampMax = "5"))
	int32 tactical_ap_cost_diagonal = 2;

	/** Стоимость базовой атаки бойца (очки действия AP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1", UIMax = "10", ClampMin = "1", ClampMax = "10"))
	int32 tactical_ap_cost_attack = 3;

	/** Стоимость сдвига/толкания бочки на соседнюю клетку (очки действия AP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1", UIMax = "10", ClampMin = "1", ClampMax = "10"))
	int32 tactical_ap_cost_push_barrel = 2;

	/** Стоимость смены стойки бойца (очки действия AP). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0", UIMax = "5", ClampMin = "0", ClampMax = "5"))
	int32 tactical_ap_cost_stance = 1;

	/** Бонус к шансу попадания в стойке ПРИСЕВ (+15%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.0", UIMax = "0.5", ClampMin = "0.0", ClampMax = "0.5", Delta = "0.05"))
	float tactical_stance_crouch_acc_bonus = 0.15f;

	/** Бонус к шансу попадания в стойке ЛЁЖА (+30%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.0", UIMax = "0.5", ClampMin = "0.0", ClampMax = "0.5", Delta = "0.05"))
	float tactical_stance_prone_acc_bonus = 0.30f;

	/** Базовый урон атаки бойца отряда в пошаговом бою. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "5.0", UIMax = "150.0", ClampMin = "5.0", ClampMax = "150.0", Delta = "1.0"))
	float tactical_squad_base_damage = 30.0f;

	/** Базовый урон атаки врага в пошаговом бою. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "5.0", UIMax = "150.0", ClampMin = "5.0", ClampMax = "150.0", Delta = "1.0"))
	float tactical_enemy_base_damage = 18.0f;

	/** Урон залпа оборонительной турели в пошаговом бою. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "5.0", UIMax = "100.0", ClampMin = "5.0", ClampMax = "100.0", Delta = "1.0"))
	float tactical_turret_damage = 25.0f;

	/** Дальность поражения оборонительной турели в клетках сетки. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1", UIMax = "15", ClampMin = "1", ClampMax = "15"))
	int32 tactical_turret_range = 5;

	/** Урон детонации бочки при подрыве 3х3 клетки. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "10.0", UIMax = "200.0", ClampMin = "10.0", ClampMax = "200.0", Delta = "5.0"))
	float tactical_barrel_damage = 80.0f;

	/** Множитель входящего урона в стойке ПРИСЕВ (Crouch = -30% урона). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.1", UIMax = "1.0", ClampMin = "0.1", ClampMax = "1.0", Delta = "0.05"))
	float tactical_stance_crouch_dmg_mult = 0.70f;

	/** Множитель входящего урона в стойке ЛЁЖА (Prone = -50% урона). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.1", UIMax = "1.0", ClampMin = "0.1", ClampMax = "1.0", Delta = "0.05"))
	float tactical_stance_prone_dmg_mult = 0.50f;

	/** Множитель урона при ударе в спину (Rear Arc, x1.75 с полным игнорированием брони). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1.0", UIMax = "3.0", ClampMin = "1.0", ClampMax = "3.0", Delta = "0.05"))
	float tactical_rear_attack_multiplier = 1.75f;

	/** Множитель урона при ударе с фланга (Flank Arc, x1.25 со срезом брони на 50%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "1.0", UIMax = "2.5", ClampMin = "1.0", ClampMax = "2.5", Delta = "0.05"))
	float tactical_flank_attack_multiplier = 1.25f;

	/** Время удержания клавиши Пробел для входа/выхода из пошагового боя Gorky 17 (секунды, по умолчанию 1.5с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.3", UIMax = "5.0", ClampMin = "0.3", ClampMax = "5.0", Delta = "0.1"))
	float tactical_hold_space_duration = 1.5f;

	/** Задержка от начала анимации атаки врага до момента нанесения урона и реакции персонажа (секунды, по умолчанию 0.45с). Если <= 0.0, урон наносится строго после завершения полного клипа анимации. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.0", UIMax = "3.0", ClampMin = "0.0", ClampMax = "3.0", Delta = "0.05"))
	float tactical_enemy_hit_delay = 0.45f;

	/** Принудительная общая длительность фазы атаки врага (секунды). Если 0.0, используется длина анимации из клипа. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.0", UIMax = "5.0", ClampMin = "0.0", ClampMax = "5.0", Delta = "0.1"))
	float tactical_enemy_attack_duration = 0.0f;

	/** Пауза после удара врага перед началом отхода назад (секунды, по умолчанию 0.35с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.05", UIMax = "2.0", ClampMin = "0.05", ClampMax = "2.0", Delta = "0.05"))
	float tactical_enemy_retreat_delay = 0.35f;

	/** Тактическая пауза между завершением хода одного врага и началом хода следующего (секунды, по умолчанию 0.25с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.05", UIMax = "2.0", ClampMin = "0.05", ClampMax = "2.0", Delta = "0.05"))
	float tactical_enemy_turn_interval = 0.25f;

	/** Максимальное количество использований пошагового боя за одну волну (-1 = без ограничений). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)")
	int32 tactical_uses_per_wave = -1;

	/** Пауза после залпа турели перед передачей хода врагам (секунды, по умолчанию 0.5с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Turn-Based Combat (Пошаговый бой Gorky 17)", meta = (UIMin = "0.2", UIMax = "2.0", ClampMin = "0.2", ClampMax = "2.0", Delta = "0.05"))
	float tactical_turret_shot_delay = 0.5f;

	/** Скорость мягкого слежения камеры в пошаговом бою при выходе за пределы Deadzone (по умолчанию 2.5). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тактическая камера (Пошаговый бой)", meta = (UIMin = "0.5", UIMax = "8.0", ClampMin = "0.5", ClampMax = "8.0", Delta = "0.1"))
	float tactical_camera_follow_speed = 2.5f;

	/** Радиус зоны комфорта / нечувствительности камеры в пошаговом бою (в метрах, 3.0м ≈ 2 клетки). Внутри этой зоны камера не дергается за отдельными шагами бойца. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тактическая камера (Пошаговый бой)", meta = (UIMin = "1.0", UIMax = "10.0", ClampMin = "1.0", ClampMax = "10.0", Delta = "0.5"))
	float tactical_camera_deadzone = 3.0f;

	/** Базовая амплитуда смещения камеры при выстрелах в пошаговом бою (в viewport offset). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тряска камеры в бою (Camera Shake)", meta = (UIMin = "0.02", UIMax = "1.0", ClampMin = "0.02", ClampMax = "1.0", Delta = "0.01"))
	float camera_shake_amplitude = 0.18f;

	/** Мощность (сила отдачи/травмы 0..1) тряски камеры при выстреле из винтовки (M16). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тряска камеры в бою (Camera Shake)", meta = (UIMin = "0.05", UIMax = "1.0", ClampMin = "0.05", ClampMax = "1.0", Delta = "0.01"))
	float camera_shake_power_rifle = 0.35f;

	/** Мощность (сила отдачи/травмы 0..1) тряски камеры при выстреле из пистолета. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тряска камеры в бою (Camera Shake)", meta = (UIMin = "0.05", UIMax = "1.0", ClampMin = "0.05", ClampMax = "1.0", Delta = "0.01"))
	float camera_shake_power_pistol = 0.20f;

	/** Мощность (сила отдачи/травмы 0..1) тряски камеры при выстреле из турели. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тряска камеры в бою (Camera Shake)", meta = (UIMin = "0.05", UIMax = "1.0", ClampMin = "0.05", ClampMax = "1.0", Delta = "0.01"))
	float camera_shake_power_turret = 0.28f;

	/** Скорость затухания тряски камеры (единиц травмы в секунду). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тряска камеры в бою (Camera Shake)", meta = (UIMin = "1.0", UIMax = "15.0", ClampMin = "1.0", ClampMax = "15.0", Delta = "0.5"))
	float camera_shake_decay = 4.0f;

	/** Базовая частота генератора шума тряски. */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Тряска камеры в бою (Camera Shake)", meta = (UIMin = "10.0", UIMax = "100.0", ClampMin = "10.0", ClampMax = "100.0", Delta = "5.0"))
	float camera_shake_frequency = 45.0f;

	/** Порог холода (в %), выше которого начинается риск осечки оружия (по умолчанию 60.0%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Холод и оружие в Real-Time (Misfire & Freeze)", meta = (UIMin = "30.0", UIMax = "90.0", ClampMin = "30.0", ClampMax = "90.0", Delta = "5.0"))
	float realtime_cold_misfire_threshold = 60.0f;

	/** Максимальный шанс осечки оружия при 100% холода (по умолчанию 0.30 = 30%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Холод и оружие в Real-Time (Misfire & Freeze)", meta = (UIMin = "0.05", UIMax = "0.80", ClampMin = "0.05", ClampMax = "0.80", Delta = "0.05"))
	float realtime_cold_misfire_max_chance = 0.30f;

	/** Порог глубокого замерзания оружия (в %), при котором стрельба блокируется до согревания у тепла (по умолчанию 90.0%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Холод и оружие в Real-Time (Misfire & Freeze)", meta = (UIMin = "75.0", UIMax = "100.0", ClampMin = "75.0", ClampMax = "100.0", Delta = "5.0"))
	float realtime_cold_weapon_freeze_threshold = 90.0f;

	/** Задержка передёргивания затвора после обычной осечки (в секундах, по умолчанию 0.45с). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Холод и оружие в Real-Time (Misfire & Freeze)", meta = (UIMin = "0.1", UIMax = "1.5", ClampMin = "0.1", ClampMax = "1.5", Delta = "0.05"))
	float realtime_cold_misfire_delay = 0.45f;

	/** Максимальный штраф к меткости в real-time от дрожи рук при 100% холода (по умолчанию -0.30 = -30%). */
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Холод и оружие в Real-Time (Misfire & Freeze)", meta = (UIMin = "0.05", UIMax = "0.60", ClampMin = "0.05", ClampMax = "0.60", Delta = "0.05"))
	float realtime_cold_aim_penalty_max = 0.30f;
};
