"""Generates Source/CodexTactics/Public/Data/GameBalanceConfig.h from the Godot resources/game_balance_config.gd.

Every @export of GameBalanceConfig becomes a typed UPROPERTY under its Godot name, grouped like the Godot inspector
(@export_group / @export_subgroup -> Category "Group|Subgroup"), with the ## comment as the tooltip and @export_range as
the slider / clamp. Values live in the DA_Balance / DA_GameBalanceConfig assets (Unreal is the master copy since
2026-10-01, see Scripts/Editor/import_balance.py); this script only refreshes the field list when Godot adds or
changes parameters. Plain Python (no editor):
  python Scripts/generate_balance_config.py
"""
import os
import re

GODOT = r"C:\Users\Zephyrus15Duo\Documents\Codex\godot-test-01"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Source", "CodexTactics", "Public", "Data",
                   "GameBalanceConfig.h")

EXPORT = re.compile(r'^@export(?:_range\(([^)]*)\))?\s+var\s+(\w+)\s*:\s*(float|int|bool)\s*=\s*([^#:\n]+?)\s*:?\s*(?:#.*)?$')
GROUP = re.compile(r'^@export_(group|subgroup)\("([^"]*)"')


def clean(text):
    """Category text without emoji (the editor font has none) and without the '|' separator."""
    text = "".join(ch for ch in text if ord(ch) < 0x2000 or 0x2010 <= ord(ch) <= 0x206F)
    return re.sub(r"\s+", " ", text.replace("|", "/")).strip()


def cpp_value(kind, raw):
    raw = raw.strip()
    if kind == "bool":
        return raw
    if kind == "int":
        return str(int(float(raw)))
    value = raw if ("." in raw or "e" in raw.lower()) else raw + ".0"
    return value + "f"


def range_meta(args, kind):
    parts = [p.strip() for p in args.split(",")]
    numbers = [p for p in parts if re.fullmatch(r"-?[0-9.]+", p)]
    flags = [p.strip('"') for p in parts if p.startswith('"')]
    meta = []
    if len(numbers) >= 2:
        low, high = numbers[0], numbers[1]
        meta += [f'UIMin = "{low}"', f'UIMax = "{high}"']
        if "or_less" not in flags:
            meta.append(f'ClampMin = "{low}"')
        if "or_greater" not in flags:
            meta.append(f'ClampMax = "{high}"')
    if len(numbers) >= 3 and kind == "float":
        meta.append(f'Delta = "{numbers[2]}"')
    return meta


source = open(os.path.join(GODOT, "resources", "game_balance_config.gd"), encoding="utf-8").read().replace("\r\n", "\n")
group, subgroup = "", ""
doc = []
fields = []
for line in source.split("\n"):
    stripped = line.strip()
    g = GROUP.match(stripped)
    if g:
        if g.group(1) == "group":
            group, subgroup = clean(g.group(2)), ""
        else:
            subgroup = clean(g.group(2))
        doc = []
        continue
    if stripped.startswith("##"):
        doc.append(stripped[2:].strip())
        continue
    m = EXPORT.match(stripped)
    if m:
        range_args, name, kind, default = m.groups()
        category = "|".join(p for p in (group or "Прочее", subgroup) if p)
        fields.append((name, kind, cpp_value(kind, default), category, list(doc),
                       range_meta(range_args, kind) if range_args else []))
    if stripped and not stripped.startswith("#"):
        doc = []

out = [
    "// GENERATED by Scripts/generate_balance_config.py from the Godot resources/game_balance_config.gd — do not edit by",
    "// hand (re-run the script when Godot adds parameters). The values live in /Game/Data/Balance/DA_GameBalanceConfig",
    "// and DA_Balance and are tuned there (Unreal is the master copy since 2026-10-01).",
    "",
    "#pragma once",
    "",
    "#include \"CoreMinimal.h\"",
    "#include \"Data/GodotBalanceAsset.h\"",
    "",
    "#include \"GameBalanceConfig.generated.h\"",
    "",
    "/**",
    " * The Godot GameBalanceConfig inspector in Unreal: every exported parameter as a typed field under its Godot name,",
    " * grouped like the Godot @export_group sections. UGodotBalanceAsset::GetNumber reads these fields by name, so the",
    " * game picks up edits made in the asset. Godot reference: resources/game_balance_config.gd.",
    " */",
    "UCLASS(BlueprintType)",
    "class CODEXTACTICS_API UGameBalanceConfig : public UGodotBalanceAsset",
    "{",
    "\tGENERATED_BODY()",
    "",
    "public:",
]
cpp_type = {"float": "float", "int": "int32", "bool": "bool"}
for name, kind, default, category, doc, meta in fields:
    text = " ".join(doc).replace("*/", "* /") or name
    out.append(f"\t/** {text} */")
    meta_text = f", meta = ({', '.join(meta)})" if meta else ""
    out.append(f'\tUPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "{category}"{meta_text})')
    out.append(f"\t{cpp_type[kind]} {name} = {default};")
    out.append("")
out[-1] = "};"
out.append("")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(out))
print(f"{len(fields)} fields, {len({f[3] for f in fields})} categories -> {os.path.normpath(OUT)}")
